name: TheAnswer.CI

on: [push, pull_request]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: |
        dotnet restore
        dotnet msbuild TheAnswer/WrapThat.csproj -nologo -getProperty:MinVerVersion
    - name: Build
      run: dotnet build --configuration Release --no-restore --verbosity normal
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal --configuration Release
